### ISSUE TITLE
JS error in book.js

### ISSUE THREAD

**Issue by topcowmoo** [Jason897571/Magical-Book-Browser#22]
book.js:95 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'thumbnail')
    at handleResponse (book.js:95:48)
    at book.js:83:9

**Comment by topcowmoo** [comment]
Fixed error by adding optional chaining (?.) operators to handle cases where these properties are undefined.

line 95 imageLinks: item.volumeInfo.imageLinks?.thumbnail,
